version: "3.7"

services:
  caddy:
    container_name: caddy
    image: caddy:alpine
    # build: ./caddy
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro,Z
      - caddy_data:/data
      - caddy_config:/config
      - ./..:/srv/sito:ro,Z
      - phpmyadmin:/srv/phpmyadmin
    restart: unless-stopped
  php-fpm:
    container_name: php-fpm
    build: ./php-fpm
    volumes:
      - ./..:/var/www/html:ro,Z
    restart: unless-stopped
  mariadb:
    container_name: mariadb
    image: mariadb:10.6.7
    ports:
      - "3306:3306"
    env_file:
      - ./mariadb/mariadb.env
    volumes:
      - mariadb:/var/lib/mysql
    restart: unless-stopped
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin:fpm-alpine
    env_file:
      - ./phpmyadmin/phpmyadmin.env
    volumes:
      - phpmyadmin:/var/www/html
    restart: unless-stopped

volumes:
  caddy_data:
    external: true
  caddy_config:
  phpmyadmin:
  mariadb:
