# This workflow will run accessibility audits.
# It will run on dispatch, when Action is updated or once per push.

name: A11y audit

on:
  workflow_call:
    inputs:
      target-branch:
        required: true
        default: 'dev'
        type: string
  workflow_dispatch:

jobs:
  a11yChecker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
      - name: A11y Evaluation
        uses: a11ywatch/github-actions@v1.14.0
        with:
          WEBSITE_URL: ${{ secrets.WEBSITE_URL }}/${{ inputs.target-branch }}/index.php
          SITE_WIDE: true
          FIX: false
          SUBDOMAINS: false
          TLD: true
          FAIL_WARNINGS_COUNT: 0
          FAIL_ERRORS_COUNT: 0
          LIST: true
          UPGRADE: true
          COMPUTER_VISION_ENDPOINT: false
      - name: Output JSON
        run: a11ywatch -r > "${GITHUB_STEP_SUMMARY}"
 
