# This workflow will use Muffet to check for broken links.
# It will run on dispatch, when Action is updated or once a day at midnight.

name: Broken links

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - dev
  # push:
  #   paths:
  #     - .github/workflows/check-broken-links.yml
  # schedule:
  #   - cron: '0 0 * * *'

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to v3
        uses: actions/checkout@v3
      - name: Link Checker
        uses: lycheeverse/lychee-action@v1.5.4
        with:
          args: --verbose --no-progress './**/*.html'
          fail: true # Fail action on broken links
