# This workflow will use Lychee for broken links checking.
# It will run on dispatch, on push (main + dev).
# See: https://github.com/lycheeverse/lychee-action

name: Broken links

on:
  workflow_call:
    inputs:
      target-branch:
        required: true
        type: string
  workflow_dispatch:
  push:
    branches:
      - main
      - dev
    paths:
      - .github/workflows/check-broken-links.yml

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
      - name: Link Checker
        uses: lycheeverse/lychee-action@v1.5.4
        with:
          args: --verbose --no-progress './**/*.html' # can be an URL
          fail: true # Fail action on broken links

