# This workflow will deploy the entire branch to our remote system.
# Uses rsync.
# It will run on dispatch, on push, on PR.
# See: https://zellwk.com/blog/github-actions-deploy/
#      https://github.com/marketplace/actions/rsync-deployments-action

name: Sync to remote

on:
  push:
    paths-ignore:
      - '.github/**'
      - '.configs/**'
      - '.editorconfig'
      - '.gitignore'
      - 'README.md'
      - 'LICENSE'
  pull_request:
  workflow_dispatch:

jobs:
  deploy:
    name: Remote deployment
    runs-on: ubuntu-latest
    outputs:
      current_branch: ${{ steps.branch-name.outputs.current_branch }}
    steps:
    - name: Checkout branch
      uses: actions/checkout@v3
    - name: Get branch name
      id: branch-name
      uses: tj-actions/branch-names@v6
    - name: Save branch name
      run: echo "branch=${{ steps.branch-name.outputs.current_branch }}" >> $GITHUB_OUTPUT
    - name: Deploy
      uses: burnett01/rsync-deployments@5.2.1
      with:
        switches: -avzr --delete --exclude=".github" --exclude=".git"
        path: /
        remote_path: /home/azureuser/sito/${{ steps.branch-name.outputs.current_branch }}
        remote_host: ${{ secrets.SSH_HOSTNAME }}
        remote_port: ${{ secrets.SSH_PORT }}
        remote_user: ${{ secrets.SSH_USER }}
        remote_key:  ${{ secrets.SSH_PRIVATE_KEY }}
  accessibility-audit:
    name: Accessibility audit
    needs: deploy
    uses: ggardin/tecweb/.github/workflows/a11y-audit.yml@dev
    with:
      target-branch: ${{ needs.deploy.outputs.current_branch }}
    secrets:
      inherit
  broken-links-check:
    name: Check broken links
    needs: deploy
    uses: ggardin/tecweb/.github/workflows/check-broken-links.yml@dev
    with:
      target-branch: ${{ needs.deploy.outputs.current_branch }}
    secrets:
      inherit
  pagespeed-audit:
    name: PageSpeed Insights
    needs: deploy
    uses: ggardin/tecweb/.github/workflows/check-pagespeed-performance.yml@dev
    with:
      target-branch: ${{ needs.deploy.outputs.current_branch }}
    secrets:
      inherit
