# This workflow will validate HTML and CSS.
# It will run on dispatch, on push.
# See: https://github.com/Cyb3r-Jak3/html5validator-action

name: HTML5 validator

on:
  workflow_dispatch:
  push:

jobs:
  validator:
    runs-on: ubuntu-latest
    env:
      HTML5_ACTION_DEBUG: true
    steps:
    - name: Checkout v2
      uses: actions/checkout@v2
    - name: Validator
      uses: Cyb3r-Jak3/html5validator-action@v7.2.0
      with:
        root: ./
        css: true
        log_level: WARNING
        format: text
    - name: Upload log
      uses: actions/upload-artifact@v3
      with:
        name: validation_results
        path: validation_results.log
