# This workflow will validate HTML and CSS.
# See: https://github.com/Cyb3r-Jak3/html5validator-action

name: HTML5 validator

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - dev
    paths:
      - .github/workflows/validate-html.yml
  # schedule:
  #   - cron: '0 0 * * *'

jobs:
  validator:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
      - name: Validate
        uses: Cyb3r-Jak3/html5validator-action@v7.2.0
        with:
          config: .configs/validate-html-config.yml
      - name: Log failures
        if: failure()
        run: cat log.log > "${GITHUB_STEP_SUMMARY}"

